apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: customer-service-virtual-service
spec:
  hosts:
  - "*"
  gateways:
  - necloudnativetraining-gateway
  http:
  - match:
    - uri:
        prefix: /customer
  - fault:  # Network resilience and testing - Fault Injection
      delay:
        percentage:
          value: 0.1
        fixedDelay: 5s
    route:
    - destination:
        host: customer-service
        port:
          number: 8080
    timeout: 10s #Network resilience and testing - Timeout
    retries:     #Network resilience and testing - retries
      attempts: 3
      perTryTimeout: 2s
