apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: customerservice
spec:
  hosts:
  - "*"
  gateways:
  - ingressgateway
  http:
  - match:
    - uri:
        exact: /name
    - uri:
        prefix: /static
    - uri:
        exact: /login
    - uri:
        exact: /logout
    - uri:
        prefix: /api/v1/products
    route:
    - destination:
        host: customer-service
        port:
          number: 9080