apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: customerservice
spec:
  hosts:
  - "*"
  gateways:
  - necloudnativetraining-gateway
  http:
  - match:
    - uri:
        prefix: /customer
    route:
    - destination:
        host: customer-service
        port:
          number: 8080
