apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: customer-service-destination-rule
spec:
  host: customer-service
  trafficPolicy:
    loadBalancer:
      simple: RANDOM #ROUND_ROBIN #Load Balancing
    connectionPool:
        tcp:
          maxConnections: 100 # Circuit Breaking
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
