# Service and Deployment configuration for Customer service deployment.

##################################################################################################
# Customer service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: customer-service
  labels:
    app: customer-service
    service: customer-service
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: customer-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
  labels:
    app: customer-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-service
      version: v1
  template:
    metadata:
      labels:
        app: customer-service
        version: v1
    spec:
      containers:
      - name: customer-service
        image: quay.io/necloudnativetraining/customer-service:master
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
      env:
        - name: spring.profiles.active
          value: local
